#!/bin/sh
# run_standalone.sh - build (if needed) and run photondns standalone on this
# machine, no OpenWrt required. Ctrl-C to stop.
#
# usage:   ./run_standalone.sh [config.toml]
#   with no argument a demo config is generated (DoT upstreams, cache on,
#   listen 127.0.0.1:15533, API http://127.0.0.1:8053).
#
# env:  LISTEN=127.0.0.1:15533  API=127.0.0.1:8053  REBUILD=1
set -e

DIR="$(cd "$(dirname "$0")" && pwd)"
BIN="$DIR/target/release/photondns"
LISTEN="${LISTEN:-127.0.0.1:15533}"
API="${API:-127.0.0.1:8053}"

export PATH="$HOME/.cargo/bin:$PATH"

if [ ! -x "$BIN" ] || [ "$REBUILD" = "1" ]; then
	echo "==> building photondns (release)"
	cargo build --release --manifest-path "$DIR/Cargo.toml" --bin photondns
fi

CONF="$1"
if [ -z "$CONF" ]; then
	CONF="${TMPDIR:-/tmp}/photondns-standalone.toml"
	cat > "$CONF" <<-EOF
	# generated by run_standalone.sh - edit or pass your own config as \$1
	# NOTE: tls:// upstreams on purpose: plain udp://:53 may be hijacked by
	# the local network (e.g. router-level DNS interception).
	[server]
	listen = ["$LISTEN"]

	[api]
	listen = "$API"

	[log]
	level = "info"

	[[group]]
	name = "main"
	upstreams = ["tls://223.5.5.5", "tls://1.1.1.1", "tls://8.8.8.8"]
	EOF
	echo "==> generated $CONF"
fi

"$BIN" -t -c "$CONF"
PORT="${LISTEN##*:}"
echo "==> try:  dig @${LISTEN%%:*} -p $PORT github.com"
echo "==> api:  curl http://$API/stats"
exec "$BIN" -c "$CONF"
